//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KSU
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contents> Contents { get; set; }
        public virtual DbSet<ContentsDisposals> ContentsDisposals { get; set; }
        public virtual DbSet<ContentsReceipts> ContentsReceipts { get; set; }
        public virtual DbSet<Disposals> Disposals { get; set; }
        public virtual DbSet<Enclosures> Enclosures { get; set; }
        public virtual DbSet<Place> Place { get; set; }
        public virtual DbSet<Reason> Reason { get; set; }
        public virtual DbSet<ReasonDisposals> ReasonDisposals { get; set; }
        public virtual DbSet<Receipts> Receipts { get; set; }
        public virtual DbSet<SourceOfAcquisition> SourceOfAcquisition { get; set; }
        public virtual DbSet<SourceOfReceipt> SourceOfReceipt { get; set; }
        public virtual DbSet<Views> Views { get; set; }
        public virtual DbSet<ViewsDisposals> ViewsDisposals { get; set; }
        public virtual DbSet<ViewsReceipts> ViewsReceipts { get; set; }
    }
}
