//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KSU
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Receipts()
        {
            this.ContentsReceipts = new HashSet<ContentsReceipts>();
            this.ViewsReceipts = new HashSet<ViewsReceipts>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int NumberInOrder { get; set; }
        public int IdSourceOfReceipt { get; set; }
        public int IdSourceOfAcquisition { get; set; }
        public string NumberDocument { get; set; }
        public System.DateTime DocumentDate { get; set; }
        public int TotalInstances { get; set; }
        public Nullable<int> Count { get; set; }
        public double Cost { get; set; }
        public Nullable<int> DocumentsNotAcceptedForBalance { get; set; }
        public int IdEnclosures { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContentsReceipts> ContentsReceipts { get; set; }
        public virtual Enclosures Enclosures { get; set; }
        public virtual SourceOfAcquisition SourceOfAcquisition { get; set; }
        public virtual SourceOfReceipt SourceOfReceipt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ViewsReceipts> ViewsReceipts { get; set; }
    }
}
